In [121]:
import pandas as pd
from sklearn import preprocessing as prep
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

from keras import layers
from keras import models
import pandas as pd

from PIL import Image
from keras.models import *
from keras.losses import *
from keras.layers import *

# Read Data

In [97]:
df = pd.read_csv("/home/mgarcia/Desktop/Data Science/DataSets/Housing.csv",header=0)

In [98]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

# Clean Data

In [122]:
#turn categorical features to numeric
#im gunna use label encoder to turn categorical feature to numerical  no = 0  yes = 1

labelEncoder = prep.LabelEncoder()

list = ["mainroad","guestroom","basement","hotwaterheating","airconditioning","prefarea","furnishingstatus"]
for i in list:
    df[i] = labelEncoder.fit_transform(df[i])

In [123]:
#split into X and Y
df.info()
Y = df["price"]
X = df.iloc[:,1:]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    int64
 6   guestroom         545 non-null    int64
 7   basement          545 non-null    int64
 8   hotwaterheating   545 non-null    int64
 9   airconditioning   545 non-null    int64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    int64
 12  furnishingstatus  545 non-null    int64
dtypes: int64(13)
memory usage: 55.5 KB

# Split and Normalize

In [125]:
scaler = MinMaxScaler()
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [126]:
X_train_norm = scaler.fit_transform(X_train)
X_test_norm = scaler.fit_transform(X_test)

In [138]:
Y_train_norm = scaler.fit_transform(np.asarray(Y_train).reshape(-1,1))
Y_test_norm = scaler.fit_transform(np.asarray(Y_test).reshape(-1,1))

# Model

In [140]:
model = Sequential()

layer1 = Dense(12,activation="relu",input_shape=(12,))

layer2 = Dense(50,activation="relu")

layer3 = Dense(100,activation="relu")

layer5 = Dense(1,activation="linear")

model.add(layer1)
model.add(layer2)
model.add(layer3)

model.add(layer5)

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.fit(X_train_norm,Y_train_norm,batch_size=128,epochs=120)

model.summary()

Epoch 1/120
4/4 [==============================] - 0s 1ms/step - loss: 0.1157 - mae: 0.1157
Epoch 2/120
4/4 [==============================] - 0s 2ms/step - loss: 0.1010 - mae: 0.1010
Epoch 3/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0953 - mae: 0.0953
Epoch 4/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0900 - mae: 0.0900
Epoch 5/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0862 - mae: 0.0862
Epoch 6/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0840 - mae: 0.0840
Epoch 7/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0821 - mae: 0.0821
Epoch 8/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0796 - mae: 0.0796
Epoch 9/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0776 - mae: 0.0776
Epoch 10/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0767 - mae: 0.0767
Epoch 11/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0741 - mae: 0.0741
Epoch 12/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0733 - mae: 0.0733
Epoch 13/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0718 - mae: 0.0718
Epoch 14/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0708 - mae: 0.0708
Epoch 15/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0697 - mae: 0.0697
Epoch 16/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0690 - mae: 0.0690
Epoch 17/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0675 - mae: 0.0675
Epoch 18/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0672 - mae: 0.0672
Epoch 19/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0670 - mae: 0.0670
Epoch 20/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0666 - mae: 0.0666
Epoch 21/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0652 - mae: 0.0652
Epoch 22/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0644 - mae: 0.0644
Epoch 23/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0641 - mae: 0.0641
Epoch 24/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0635 - mae: 0.0635
Epoch 25/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0620 - mae: 0.0620
Epoch 26/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0613 - mae: 0.0613
Epoch 27/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0610 - mae: 0.0610
Epoch 28/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0604 - mae: 0.0604
Epoch 29/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0606 - mae: 0.0606
Epoch 30/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0598 - mae: 0.0598
Epoch 31/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0597 - mae: 0.0597
Epoch 32/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0595 - mae: 0.0595
Epoch 33/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0602 - mae: 0.0602
Epoch 34/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0609 - mae: 0.0609
Epoch 35/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0646 - mae: 0.0646
Epoch 36/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0588 - mae: 0.0588
Epoch 37/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0573 - mae: 0.0573
Epoch 38/120
4/4 [==============================] - 0s 2ms/step - loss: 0.0570 - mae: 0.0570
Epoch 39/120
4/4 [==============================] - 0s 2ms/step - loss: 0.0580 - mae: 0.0580
Epoch 40/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0594 - mae: 0.0594
Epoch 41/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0572 - mae: 0.0572
Epoch 42/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0572 - mae: 0.0572
Epoch 43/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0563 - mae: 0.0563
Epoch 44/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0561 - mae: 0.0561
Epoch 45/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0558 - mae: 0.0558
Epoch 46/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0551 - mae: 0.0551
Epoch 47/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0542 - mae: 0.0542
Epoch 48/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0539 - mae: 0.0539
Epoch 49/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0541 - mae: 0.0541
Epoch 50/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0537 - mae: 0.0537
Epoch 51/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0534 - mae: 0.0534
Epoch 52/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0530 - mae: 0.0530
Epoch 53/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0530 - mae: 0.0530
Epoch 54/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0531 - mae: 0.0531
Epoch 55/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0539 - mae: 0.0539
Epoch 56/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0537 - mae: 0.0537
Epoch 57/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0550 - mae: 0.0550
Epoch 58/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0553 - mae: 0.0553
Epoch 59/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0542 - mae: 0.0542
Epoch 60/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0542 - mae: 0.0542
Epoch 61/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0549 - mae: 0.0549
Epoch 62/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0533 - mae: 0.0533
Epoch 63/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0526 - mae: 0.0526
Epoch 64/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0534 - mae: 0.0534
Epoch 65/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0517 - mae: 0.0517
Epoch 66/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0520 - mae: 0.0520
Epoch 67/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0509 - mae: 0.0509
Epoch 68/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0511 - mae: 0.0511
Epoch 69/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0512 - mae: 0.0512
Epoch 70/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0510 - mae: 0.0510
Epoch 71/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0513 - mae: 0.0513
Epoch 72/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0501 - mae: 0.0501
Epoch 73/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0498 - mae: 0.0498
Epoch 74/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0498 - mae: 0.0498
Epoch 75/120
4/4 [==============================] - 0s 987us/step - loss: 0.0497 - mae: 0.0497
Epoch 76/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0493 - mae: 0.0493
Epoch 77/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0494 - mae: 0.0494
Epoch 78/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0505 - mae: 0.0505
Epoch 79/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0497 - mae: 0.0497
Epoch 80/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0496 - mae: 0.0496
Epoch 81/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0521 - mae: 0.0521
Epoch 82/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0529 - mae: 0.0529
Epoch 83/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0583 - mae: 0.0583
Epoch 84/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0589 - mae: 0.0589
Epoch 85/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0540 - mae: 0.0540
Epoch 86/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0524 - mae: 0.0524
Epoch 87/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0529 - mae: 0.0529
Epoch 88/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0506 - mae: 0.0506
Epoch 89/120

4/4 [==============================] - 0s 1ms/step - loss: 0.0507 - mae: 0.0507
Epoch 90/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0522 - mae: 0.0522
Epoch 91/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0491 - mae: 0.0491
Epoch 92/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0481 - mae: 0.0481
Epoch 93/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0482 - mae: 0.0482
Epoch 94/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0481 - mae: 0.0481
Epoch 95/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0478 - mae: 0.0478
Epoch 96/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0490 - mae: 0.0490
Epoch 97/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0494 - mae: 0.0494
Epoch 98/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0502 - mae: 0.0502
Epoch 99/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0487 - mae: 0.0487
Epoch 100/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0488 - mae: 0.0488
Epoch 101/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0491 - mae: 0.0491
Epoch 102/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0496 - mae: 0.0496
Epoch 103/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0486 - mae: 0.0486
Epoch 104/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0479 - mae: 0.0479
Epoch 105/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0472 - mae: 0.0472
Epoch 106/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0471 - mae: 0.0471
Epoch 107/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0466 - mae: 0.0466
Epoch 108/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0468 - mae: 0.0468
Epoch 109/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0473 - mae: 0.0473
Epoch 110/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0465 - mae: 0.0465
Epoch 111/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0474 - mae: 0.0474
Epoch 112/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0474 - mae: 0.0474
Epoch 113/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0463 - mae: 0.0463
Epoch 114/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0465 - mae: 0.0465
Epoch 115/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0464 - mae: 0.0464
Epoch 116/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0463 - mae: 0.0463
Epoch 117/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0459 - mae: 0.0459
Epoch 118/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0485 - mae: 0.0485
Epoch 119/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0472 - mae: 0.0472
Epoch 120/120
4/4 [==============================] - 0s 1ms/step - loss: 0.0477 - mae: 0.0477
Model: "sequential_21"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_81 (Dense)            (None, 12)                156

 dense_82 (Dense)            (None, 50)                650

 dense_83 (Dense)            (None, 100)               5100

 dense_84 (Dense)            (None, 1)                 101

=================================================================
Total params: 6007 (23.46 KB)
Trainable params: 6007 (23.46 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

# Evaluate

In [141]:
model.evaluate(X_test_norm,Y_test_norm)

4/4 [==============================] - 0s 1ms/step - loss: 0.0931 - mae: 0.0931

[0.09305363148450851, 0.09305363148450851]

In [142]:
Y_test

464    3080000
437    3290000
111    6090000
28     8400000
280    4270000
        ...
478    2940000
341    3850000
379    3633000
266    4403000
71     6755000
Name: price, Length: 109, dtype: int64

In [156]:
house=X_test_norm[2,:]

In [146]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
464,4500,2,1,2,1,0,0,1,0,1,0,1
437,5880,3,1,1,1,0,0,0,0,1,0,2
111,8372,3,1,3,1,0,0,0,1,2,0,2
28,7950,5,2,2,1,0,1,1,0,2,0,2
280,6360,2,1,2,1,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
478,3600,3,1,2,0,0,0,0,0,1,0,2
341,3180,2,2,1,1,0,1,0,0,2,0,1
379,3520,3,1,1,1,0,0,0,0,2,1,2
266,4880,3,1,1,1,0,0,0,0,2,1,2
71,6000,4,2,4,1,0,0,0,1,0,0,2

In [157]:
y = Y_test.iloc[2]

In [158]:
y

6090000

In [160]:
awn = model.predict(house.reshape(1,-1))

1/1 [==============================] - 0s 32ms/step

In [161]:
print(awn)

[[0.40037033]]

In [162]:
scaler.inverse_transform(awn)

array([[5827448.]], dtype=float32)